apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lwweb
    app.kubernetes.io/instance: myargoapp1
  name: lwweb
spec:
  ports:
  - port: 81
    protocol: TCP
    targetPort: 81
  selector:
    app: lwweb
  type: LoadBalancer
status:
  loadBalancer: {}
