apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lwwebappstaging
spec:
  project: default
  destination:
    server: https://192.168.229.158:8443
    namespace: default
  source:
    repoURL: https://github.com/KabraJiii/multienv-argocd-session-7.git
    path: staging
    targetRevision: main
