apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-app-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: prodcluster
        url: https://192.168.233.130:8443
      - cluster: staging
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/vimallinuxworld13/argocd_training_2024_code.git
        targetRevision: main
        path: 'multienv/{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: default
